import { govPoolABI } from '../abi';

export const moonriverStakePools = [
  {
    id: 'moo_finn-wmovr-finn-huckleberry',
    name: 'Huckleberry',
    assets: ['FINN', 'MOVR'],
    token: 'mooFinnMOVR-FINN',
    tokenDecimals: 18,
    tokenAddress: '0xFaA15A1B4DAB85d35e912f88127b9986638a1265',
    tokenOracle: 'lps',
    tokenOracleId: 'finn-wmovr-finn',
    earnedToken: 'FINN',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0x9A92B5EBf1F6F6f7d93696FCD44e5Cf75035A756',
    earnContractAddress: '0x405EE7F4f067604b787346bC22ACb66b06b15A4B',
    earnContractAbi: govPoolABI,
    earnedOracle: 'tokens',
    earnedOracleId: 'FINN',
    partnership: true,
    status: 'active',
    isMooStaked: true,
    periodFinish: 1639217938,
    partners: [
      {
        logo: 'stake/huckleberry/logo.png',
        background: 'stake/huckleberry/bg.png',
        text: 'Huckleberry is a community driven AMM crosschain DEX built on Moonriver, where every single feature is designed around creating value for FINN holders. This is seen in everything from its high-APR Rivers, risk-free Excursions and the FINN token itself. FINN has a special feature called Passive Sailin’, where 1% of every FINN transaction is shared among all FINN holders. This means that all our users are constantly earning just by holding FINN.',
        website: 'https://www.huckleberry.finance/',
        social: {
          telegram: 'https://t.me/HuckleberryDex',
          twitter: 'https://twitter.com/HuckleberryDEX',
        },
      },
    ],
  },

  {
    id: 'moo_solarbeam-frax-wmovr-2-huckleberry',
    name: 'Huckleberry',
    assets: ['FRAX', 'MOVR'],
    token: 'mooSolarFRAX-WMOVR',
    tokenDecimals: 18,
    tokenAddress: '0xf8e9774AE3cc7aE3eE11161cC1313252A0784E18',
    tokenOracle: 'lps',
    tokenOracleId: 'solarbeam-frax-wmovr-2',
    earnedToken: 'FINN',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0x9A92B5EBf1F6F6f7d93696FCD44e5Cf75035A756',
    earnContractAddress: '0x3C9C884eFAB85c44D675039de227b3Dd275c360e',
    earnContractAbi: govPoolABI,
    earnedOracle: 'tokens',
    earnedOracleId: 'FINN',
    partnership: true,
    status: 'active',
    isMooStaked: true,
    periodFinish: 1638526810,
    partners: [
      {
        logo: 'stake/huckleberry/logo.png',
        background: 'stake/huckleberry/bg.png',
        text: 'Huckleberry is a community driven AMM crosschain DEX built on Moonriver, where every single feature is designed around creating value for FINN holders. This is seen in everything from its high-APR Rivers, risk-free Excursions and the FINN token itself. FINN has a special feature called Passive Sailin’, where 1% of every FINN transaction is shared among all FINN holders. This means that all our users are constantly earning just by holding FINN.',
        website: 'https://www.huckleberry.finance/',
        social: {
          telegram: 'https://t.me/HuckleberryDex',
          twitter: 'https://twitter.com/HuckleberryDEX',
        },
      },
    ],
  },
];
